# Generated by Django 6.0.4 on 2026-06-08 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0002_item_icone'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='avatar',
            field=models.CharField(default='🧑\u200d💻', max_length=10, verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='bio',
            field=models.TextField(blank=True, default='', verbose_name='Bio'),
        ),
    ]
