# Generated by Django 6.0.4 on 2026-05-27 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100, verbose_name='Usuário')),
                ('matricula', models.IntegerField(unique=True, verbose_name='Matrícula')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('telefone', models.IntegerField(unique=True, verbose_name='Telefone')),
            ],
        ),
        migrations.CreateModel(
            name='Reivindicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=50, verbose_name='Item_Reivindicação')),
                ('descricao_prova', models.TextField()),
                ('status_Reivindicacao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do item encontrado')),
                ('descricao', models.TextField(verbose_name='Descrição do item encontrado')),
                ('local', models.CharField(choices=[('biblioteca', 'Biblioteca'), ('cantina', 'Cantina'), ('laboratorio', 'Laboratório'), ('sala_aula', 'Sala de Aula'), ('estacionamento', 'Estacionamento'), ('banheiro', 'Banheiro'), ('outro', 'Outro')], max_length=20, verbose_name='Local onde o item foi encontrado')),
                ('situacao_Item', models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado')], max_length=20)),
                ('status_Item', models.CharField(choices=[('ativo', 'Ativo'), ('reivindicado', 'Reivindicado'), ('entregue', 'Entregue')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='itens/', verbose_name='Imagem do item encontrado')),
                ('data_encontro', models.DateField(verbose_name='Data em que o item foi encontrado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Usuário', to='entidades.aluno', verbose_name='Cadastrado_por')),
            ],
        ),
    ]
