# Generated by Django 6.0.4 on 2026-05-29 17:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.IntegerField(unique=True, verbose_name='Matrícula')),
                ('curso', models.CharField(max_length=100, verbose_name='Curso')),
                ('telefone', models.CharField(max_length=15, unique=True, verbose_name='Telefone')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Aluno', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome do item encontrado')),
                ('descricao', models.TextField(verbose_name='Descrição do item encontrado')),
                ('local', models.CharField(choices=[('biblioteca', 'Biblioteca'), ('cantina', 'Cantina'), ('laboratorio', 'Laboratório'), ('sala_aula', 'Sala de Aula'), ('estacionamento', 'Estacionamento'), ('banheiro', 'Banheiro'), ('outro', 'Outro')], max_length=20, verbose_name='Local onde o item foi encontrado')),
                ('situacao_Item', models.CharField(choices=[('perdido', 'Perdido'), ('encontrado', 'Encontrado')], max_length=20)),
                ('status_Item', models.CharField(choices=[('ativo', 'Ativo'), ('reivindicado', 'Reivindicado'), ('entregue', 'Entregue')], max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='itens/', verbose_name='Imagem do item encontrado')),
                ('data_encontro', models.DateField(verbose_name='Data em que o item foi encontrado')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cadastrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to=settings.AUTH_USER_MODEL, verbose_name='Cadastrado_por')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Itens',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='Reivindicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_prova', models.TextField(verbose_name='Prova que o Item é seu')),
                ('status_Reivindicacao', models.CharField(choices=[('pendente', 'Pendente'), ('aprovada', 'Aprovada'), ('recusada', 'Recusada')], default='pendente', max_length=20, verbose_name='Status reivindicacao')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reivindicacao', to='entidades.item', verbose_name='Item reivindicacao')),
                ('requerente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reivindicacoes', to=settings.AUTH_USER_MODEL, verbose_name='Requerente')),
            ],
            options={
                'verbose_name': 'Reivindicação',
                'verbose_name_plural': 'Reivindicações',
            },
        ),
    ]
