# Generated by Django 6.0.4 on 2026-06-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='icone',
            field=models.CharField(choices=[('fa-laptop', 'Eletrônicos/Notebook'), ('fa-key', 'Chaves'), ('fa-wallet', 'Carteira/Dinheiro'), ('fa-book', 'Livros/Cadernos'), ('fa-mobile-screen-button', 'Celular'), ('fa-shirt', 'Roupas/Casacos'), ('fa-glasses', 'Óculos'), ('fa-backpack', 'Bolsas/Mochilas')], default='fa-box', max_length=50, verbose_name='Ícone do item'),
        ),
    ]
