# Generated by Django 6.0.4 on 2026-06-08 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0003_aluno_avatar_aluno_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matricula',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='Matrícula'),
        ),
    ]
