# Generated by Django 6.0.4 on 2026-06-08 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0004_alter_aluno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status_Item',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('reivindicado', 'Reivindicado'), ('entregue', 'Entregue')], default='ativo', max_length=20),
        ),
    ]
